import { scryptSync, timingSafeEqual } from "crypto";
import type { AuthOptions } from "next-auth";
import CredentialsProvider from "next-auth/providers/credentials";

/**
 * Verify a password against a stored value.
 * Supports two formats:
 *   - plain text:  "mysecret"
 *   - scrypt hash: "scrypt:salt:hash"  (generated by /api/auth/hash)
 */
function verifyPassword(input: string, stored: string): boolean {
  if (stored.startsWith("scrypt:")) {
    const [, salt, hash] = stored.split(":");
    if (!salt || !hash) return false;
    try {
      const inputHash = scryptSync(input, salt, 64).toString("hex");
      return timingSafeEqual(Buffer.from(hash, "hex"), Buffer.from(inputHash, "hex"));
    } catch {
      return false;
    }
  }
  // Plain text fallback (for initial setup)
  return input === stored;
}

/**
 * Parse ADMIN_CREDENTIALS env var.
 * Format: "email:password,email2:scrypt:salt:hash"
 * The password part can contain colons (scrypt format), so we split on first colon only.
 */
function getAdmins() {
  return (process.env.ADMIN_CREDENTIALS ?? "")
    .split(",")
    .map((pair) => pair.trim())
    .filter(Boolean)
    .map((pair) => {
      const idx = pair.indexOf(":");
      return { email: pair.slice(0, idx).trim(), stored: pair.slice(idx + 1).trim() };
    })
    .filter((a) => a.email && a.stored);
}

export const authOptions: AuthOptions = {
  providers: [
    CredentialsProvider({
      name: "Admin Panel",
      credentials: {
        email: { label: "Email", type: "email" },
        password: { label: "Mot de passe", type: "password" },
      },
      async authorize(credentials) {
        if (!credentials?.email || !credentials?.password) return null;
        const admin = getAdmins().find((a) => a.email === credentials.email);
        if (!admin || !verifyPassword(credentials.password, admin.stored)) return null;
        return { id: admin.email, email: admin.email, name: admin.email.split("@")[0] };
      },
    }),
  ],
  session: { strategy: "jwt" },
  jwt: { maxAge: 8 * 60 * 60 },
  pages: { signIn: "/" },
};
